---
- name: Install NGINX Agent awk prerequisite
  ansible.builtin.package:
    name: gawk
    state: present

- name: (Alpine Linux/Debian/SLES OSs) Install NGINX Agent awk and nstat prerequisite
  ansible.builtin.package:
    name: iproute2
    state: present
  when: ansible_facts['os_family'] in ['Alpine', 'Debian', 'Suse']

- name: (Red Hat OSs) Install NGINX Agent awk and nstat prerequisite
  ansible.builtin.package:
    name: iproute
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Manage NGINX Agent repository
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/agent/setup-{{ ansible_facts['os_family'] | lower }}.yml"
  when: ansible_facts['os_family'] in ['Alpine', 'Debian', 'RedHat', 'Suse']

- name: Install NGINX Agent
  ansible.builtin.package:
    name: nginx-agent
    state: present
  notify: (Handler) Start NGINX Agent

- name: Dynamically generate NGINX Agent static configuration file
  ansible.builtin.template:
    src: nginx-agent/nginx-agent.conf.j2
    dest: /etc/nginx-agent/nginx-agent.conf
    mode: "0644"
    backup: true
  when: nginx_agent_configure | bool
  notify: (Handler) Start NGINX Agent
