---
- name: "{{ nginx_setup | capitalize }} NGINX from the distribution's package repository"
  ansible.builtin.package:
    name: "{{ nginx_distribution_package | default('nginx' + (nginx_version | default(''))) }}"
    state: "{{ nginx_state }}"
  register: _progress_status
  until: _progress_status is succeeded
  delay: 5
  retries: 5
  notify: (Handler) Run NGINX
