---
- name: Converge
  hosts: all
  tasks:
    - name: Install NGINX and NGINX Agent
      ansible.builtin.include_role:
        name: ansible-role-nginx
      vars:
        nginx_agent_enable: true
        nginx_agent_configure: true
        nginx_agent_server:
          host: agent.connect.nginx.com
          port: 443
          data_plane_key: "{{ lookup('env', 'AGENT_DATA_PLANE_KEY') }}"
        nginx_agent_tls:
          skip_verify: false
        nginx_agent_features:
          - certificates
          - file-watcher
          - metrics
        nginx_agent_labels:
          env: dev
          team: ansible
        nginx_agent_data_plane_config:
          api_url: "http://127.0.0.1:80/api"
          treat_warnings_as_errors: false
